### ISSUE TITLE
Multiple output types like esm, umd, amd?

### ISSUE THREAD

**Issue by quentincaffeino** [DylanVann/perfect-dark-mode#1]
I try opening a pr with rollup as a bundler if you are ok with it.

**Comment by quentincaffeino** [comment]
So I played with `tsdx` a little, and got it working with no problem, it exports cjs,esm and umd. The only downside is that I couldn't come up with how to combine your's default js code for exposing module on window with what was coming out of `tsdx`. I'll issue since you could do something better if you needed, I just gonna use private package for my requirements.

**Comment by DylanVann** [comment]
Hi @quentincaffeino , thanks for taking a look at this!

I think it would be best to keep `dist/index.js` easy to use as a script that can just be put in `<head>`.

For people with other needs though I've added `dist/pure.esm.js`, `dist/pure.cjs.js`, and `dist/pure.iife.js` (no AMD/UMD since `esbuild` does not support them and I want to stick with `esbuild` because it's faster than Rollup/`tsdx`).

You can import from the pure version:

```js
import {createPerfectDarkMode} from 'perfect-dark-mode'

const pdm = createPerfectDarkMode()
```

**Comment by quentincaffeino** [comment]
True, esbuild is fast)

Is it too much to ask for a class transformer? Many tools I've seen uses `.mode-%mode%` class, they allow changing that class but it's to much to change when there are multiple of them (also to much space for a generic programmer error). It would be nice if your package would allow adding function transformer to `createPerfectDarkMode` props. Something like:
```ts
declare type ClassTransformer<T> = (mode: T) => T;
export interface PerfectDarkModeOptions {
  modes?: string[]
  classTransformer?: ClassTransformer<String>
}

...

  mode.subscribe((v) => {
    if (colorMode) {
      htmlElement.classList.remove(classTransformer(colorMode))
    }
    if (v) {
      htmlElement.classList.add(classTransformer(v))
    }
    colorMode = v
  })
```

**Comment by DylanVann** [comment]
I've changed it to use `pdm-` as a prefix for those classes by default. I could make it a function but I'm trying not to add too many options because they increase the bundle size.
