### ISSUE TITLE
Be able to use .dark instead of pdm-dark on root html.

### ISSUE THREAD

**Issue by BurnedChris** [DylanVann/perfect-dark-mode#5]
This would mean that if used with tailwind css / twin.macro

you could enable all dark mode classes with .dark without any hack arounds. 

If this is currently possible i would love to know

**Comment by DylanVann** [comment]
Maybe I could make the prefix configurable. If you want a workaround this will work:

```tsx
let modePrevious;
window.__pdm__.mode.subscribe((mode) => {
  const htmlElement = document.documentElement;
  htmlElement.classList.remove(modePrevious);
  htmlElement.classList.add(mode);
  modePrevious = mode;
});
```

The mode value here is unprefixed.
